config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:create]
  resources :users
  resources :posts do
    resources :comments
  end
  root "posts#index"
  
  get "/about", to: "pages#about"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end 

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end 

  private
    def comment_params 
      params[:comment].permit(:name, :body)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index 
    @posts = Post.all.order("created_at DESC")
  end 

  def show
    @post = Post.find(params[:id])
  end

  def new 
    @post = Post.new 
  end
  
  def create 
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to @post 
    else
      render "new"
    end 
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update 
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render "edit"
    end
  end 

  def destroy 
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to root_path
  end 

  private
    def post_params 
      params.require(:post).permit(:title, :body)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
      flash[:notice] = "Welcome back, #{current_user.username}! ;)"
    else
      flash.now[:notice] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out, baiiii. See you soon! :)"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: "mel", password: "idk123", except: [:new, :create]

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
      flash[:notice] = "Welcome! Please log in with your new account :)"
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render "edit"
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment_content">
    <p class="comment_name">
      <strong><%= comment.name %></strong>
    </p>

    <p class="comment_body">
      <%= comment.body %>
    </p>

    <p class="timestamp">
      <%= time_ago_in_words(comment.created_at) %> ago
    </p>
  </div>

  <button class="delete_comment">
    <%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Sure you wanna delete da comment?" } %>
  </button>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @post.comments.build], local: true) do |form| %>

  <p>
    <%= form.label :name %><br>
    <% if current_user %>
      <%= form.text_field :name, value: current_user.username %>
    <% else %>
      <%= form.text_field :name %>
    <% end %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cucumbrr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag "Cucumbrr.png"%>
  </head>

  <body>
    <div id="sidebar">
      <h2 class="sidebar_title"><%= link_to "Cucumbrr", root_path %></h2>
      <p class="sidebar_subtitle">tumblr, but cooler</p>
      <ul>
        <li>
          <%= link_to "Posts", root_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
      </ul>
      <ul>
        <% if current_user %>
          <li>
            <%= link_to current_user.username, current_user %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log In", login_path %>
          </li>
          <li>
            <%= link_to "Sign Up", signup_path %>
          </li>
        <% end %>
      </ul>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My site</p>
        <% else %>
          <%= link_to "< Back to Post Feed", root_path %>
        <% end %>
        <div class="buttons">
          <% if current_user %>
            <button class="button">
              <%= link_to "Add Post", new_post_path %>
            </button>
            <button class="button">
              <%= link_to "Log Out", logout_path, data: { confirm: "Log out?" } %>
            </button>
          <% else %>
            <button class="button">
              <%= link_to "Log In", login_path %>
            </button>
          <% end %>
        </div>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") do %>
          <%= msg %>
        <% end %>
      <% end %>
      
      <%= yield %>
  
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div class="profile_image">
    <%= image_tag "Profile.png" %>
  </div>

  <div class="content">
    <h3>creator of cucumbrr:</h3>
    <h1>It's Pubble!</h1>
    <p>Messenger bag glossier etsy 8-bit copper mug disrupt pitchfork trust fund direct trade bicycle rights helvetica four dollar toast brunch shoreditch. Letterpress keytar mlkshk dreamcatcher slow-carb. Chia banjo air plant polaroid. Pop-up enamel pin prism try-hard. Man braid bushwick direct trade, pitchfork tbh whatever meditation cliche hashtag venmo hammock. Skateboard godard vexillologist organic gastropub keytar tote bag snackwave distillery hell of. Chartreuse four dollar toast mixtape selfies flexitarian deep v neutra, shoreditch heirloom farm-to-table.</p>

  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>

  <% if @post.errors.any? %>
    <div class="errors">
      <h2>
        <%= pluralize(@post.errors.count, "error")%> stopped this post from saving! :(
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/_welcome.html.erb
<div id="welcome_wrapper">
  <div class="welcome">
    <h1>
      Welcome to cucumbrr!
    </h1>
    <p>
      Start posting and contributing to any discussions in the comments!
    </p>
    <hr>
    <div class="user_prompt">
      <div>
        <h2>
          New here ?
        </h2>
        <button class="green_button">
          Sign up!
        </button>
      </div>
      <div>
        <h2>
          Already a user ?
        </h2>
        <button class="green_button">
          <%= link_to "Log in!", login_path %>
        </button>
      </div>
    </div>
  </div>
<h2 class="check_out">
  <span>
  Check out some of our posts
  </span>
</h2>
</div>

app/views/posts/edit.html.erb
<div class="post_form">
  <h1>Fix post</h1>

  <%= render "form" %>
</div>

app/views/posts/index.html.erb
<% if !current_user %>
  <%= render "welcome" %>
<% end %>

<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="post_title">
      <%= link_to post.title, post %>
    </h2>
    <p class="post_snippet"><%= truncate(post.body, length: 100)%></p>
    <p class="timestamp">
      <%= time_ago_in_words(post.created_at) %> ago
    </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="post_form">
  <h1>Make something</h1>

  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="post_wrapper">
  <h1 class="post_title">
    <%= @post.title %>
  </h1>

  <p class="timestamp">
    Posted <%= time_ago_in_words(@post.created_at) %> ago |
    <% if current_user %>
      <%= link_to "Edit", edit_post_path(@post) %> |
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you wanna delete?" } %>
    <% end %>
  </p>

  <p class="post_body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> comment(s)</h2>
    <hr>
    <%= render @post.comments %>
    <h3 class="comment_prompt">Feel free to comment!</h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="errors">
      <h2>Please follow field requirements:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>

  <p>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </p>

  <%= form.submit %>
<% end %>

app/views/users/edit.html.erb
<div id="user_form">
  <h1>Update Profile</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Cancel', @user %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="user_form">
  <h1>Sign up!</h1>

  <%= render 'form', user: @user %>

  <p>
    Already have an account? <%= link_to "Log in!", login_path, class: "green_link"%>
  </p>
</div>

app/views/users/show.html.erb
<div id="user_page">
  <p>
    <h1><%= @user.username %></h1>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <%= link_to 'Update Profile', edit_user_path(@user) %>
</div>